language: node_js
node_js:
- '7'
env:
  global:
    - EXTENSION_ID=hnhoenkaejcgnomfneoonfdjmignlami
    - CLIENT_ID=822187143060-7idrp32uvlf7dr58ksk7c72vsebpl7k5.apps.googleusercontent.com
    - secure: FQvGF9KDv2xsQuUFI11uLscxAPZDP6do9aRwYM3MKioKQVCq8Pe5yWJSMEdMUqKbeice0LVhsBhG4sLAR7Njjm2lfRZxmXlDwhBLPbgr5qeyU/F574R81UKfQc722yXIEeMAW9P8J4MnC9ADEB5rvPOxm3lNuUC7KZcJ06wHp5u6LzejmgA84EvLNAYy4/qV2geVJQg3+LJcmQ/p3WfojtC7ck6MVm0JdfyltWZnASMxPTd7fdLmGZcFYM+Vtueppf3HgvuWCLDyalmBfam5CGupHUj1Ps+8Q/lkdUYww8c0Cqhk/O7U3IhZaI3kKZtDXKOQhayiT6+A7mIl3VZWNjbjbXd+dtpt4lPkVQ59HXLf7jhH1Ku5upNls6uMNLSBjepEVRDQ/DaRgcbdSaD/Bj9/L4yiWe4qsY5aozsIVqF5PCSeML10que2FtkNdDSE3evnRJaczrKb5xskCTXQOasANx5ptWS64LdZ70Kti/zwiELMyS9uPsEpXU+GRRAIKDE+DxWOsSun1dHNcbhixrKOQI3S3to2sc1bKfNRbfiEXqewFNjCyUWN13K8kEWY83iMDkNvR9dklHoKV3vSNYk4ND4VbPIJ/+h+QeBqWWkpSxp/PzpSUYc/AVNi+q4lJ7k0+BYgXgMjpcAg8wIAZwxDo5GPkJgOzd6PGufCjik=
    - secure: IMBWC12thH16vqBauON3qebgfUeX8ltIE0ptns0MK0sYNjn9HVv81vsiKORAJKz9isLaG6zkIv+gD9L88CzqXqEpsL54HvH1SXGaq1i92LNGV0V5eKotzNi+gKgMGNRulaq/3Xp7ROD28Eq6Z2Jsm1mCHlS6zmGkkfIIKIv/FBh0ypfrEn7FYV2VNj1upnzs2YQDv1vc+YDkE6b5tsaftm6jVZW735ikt0FG6STeVY6dU2Dh6in40eqrn5bml4TNqglGUwqdBXIWfrIRb25JVJHVaI6/ggXoYXekEbu4dsldYDGQY5aPemNHEaGfGYHpOWodaEjFj2FAqhu8EwW1PKTnB6pHHWQ93TKfTAatzb076Unr04TlA/VzmlcBz0H+8DPg1aGfzv+csiDs1bax6RkAjzwWD96vDQk9LX3adUlxglEa9aZ37W8Pj+jfqeYVhvUHSkOfm06SFNWqBVNiKpA5Ex9yliDUJMmJgzH/yNC1EcWls8uCISe9gMdbCc3wSj063WM2XfVnQgMqDQf5nnr1zX01H+laUDVbwutneSgRNXTxxFPxmTyLWXxb0UfDfjLlkJnpHYU2OYKt7nEV+U0WuIFtYJuH/lVLLm1o9z5I1ckOb1VIoIVPlWZkVTiJZbSrKM2H8oPNBrfMcG1mO7Ve/XmuW5lQ7th0fmNhBBA=
before_install:
- npm install -g chrome-webstore-upload-cli@^1.0.0
# Only build tags
if: tag IS present
deploy:
  provider: script
  script: npm run release
  on:
    branch: master
    tags: true
