language: node_js
node_js:
- '7'
env:
  global:
    - EXTENSION_ID=hnhoenkaejcgnomfneoonfdjmignlami
    - CLIENT_ID=822187143060-7idrp32uvlf7dr58ksk7c72vsebpl7k5.apps.googleusercontent.com
    - secure: Qg5JiiXa1BLhR2eU1D9UOj1Ei/ocVUiDZwNGlxc1W4QPFC6fJkPEXhWjbDXzVjY6ReuNiiF+Ub87+nm+i7J9TokNDCHmbH1FuRHm4FfSTHQXDPiKasLfb57xuZp8JzY9knmSg2EmF9Z8SkTHwCBnC972uTxm2GxFYlnxIBF3MaYTbS2b+x23Mux86TRZ/EFn6JIRiGgClV1lQu4qThN49E4XqVOvFdG+oa6c+grB1K/03SVnKU2CXqK5zU9eRzf4wvMfwj7uBnGjxUkRB9vgOoF8scyua85sukdmwjd+eGV6nYIsjNZfo1DatS4yYtzRUs+M1LJ9SPhMLsK24Zfw29jI2HN9YCDCPFwqpJuwW5ZIfWnDdf52zgJD30Gn6pjWzmf0nkCaUelFYt6Cb1Mzi/KUj3PqSs8MRhRAa1A+oERC+Qd2sY0C/ZwjCwEr8EYoW332mOUUV0AiOTiVHZ04D2Y4rE9uCip20peL/ZHhp8oYv4myjbRpZ1F3/FyzvVfeHhMmUWQWuF4e7Oy28LGQrnZ//PhAsXoRdd1RlmKMh33m9q8F9IFZ5i5qOYtuADK8cA58z9SXOHF9IIqyuUb85MgTsHPltr6vjyX9SqcZvy7/CgZfS+OJFg6gO9tQlNWUiF4s675qFl5vll6yUW7ns/OmWmHE8MHXPVk4R5b9qpQ=
    - secure: dedKwVnmgzk4GrMVipBAqhl6XcKrKcnfn2WfbGKbkbNwVssP2G+K6A8ay7SL9ImNLJgOjuUpmOhB7OebKNHNGc5mRGG28PakRChL3FAH02Uw0Y9QV45yyGQHxaDegUfjQrKWCez7KwuTAGANuqLfqV0jRxYm1gYCHIfk+4r/xNNek8Wf1U4Xw4hSXmRGQb8BUOjntBN14KPB5bkTTePgX2zKYviIU9r33gsMqbFMHcP7MFF6JyokQEjyYNjObqlJ9UebaFCA+dsF5KpRIC1ayBimcFJcrgxyBQ/5g6p6a3lafJ3D0bYgTMENduwgxfTizBou8NJe/zR9ylseps9R913M0aAbJ+qAOZl714AJ8F692hTOoa9DtU9/THrkYRG/2FAs5F07nf89TDG3SRHSlXqltfQ0UOS1xOglLxel7T0Z2m/QtiqoStafeP3FJK2LBzlR2GWyj2xgZIRFoZQB9kIdglu/0QW4Vu45Vb/ZapsuPt1BF+Qa2Wb0+Me+HJyf0Yjs2xTgGMimy5Dk+FkMRWkbhW+7DL3mFgV9IIiHOopxG7RMWB24vV3uDwKuYZhsmb0qbHnkcB3pXot4MmNS0FdSJS+Zaq09qFSgT7Ic+uNDFojrelP6qhW+dlouojDvpWbjFU7+fXew2c8rXOnivPaXqxdQEKdbPgidqs5W4iw=
before_install:
- npm install -g chrome-webstore-upload-cli@^1.0.0
# Only build tags
if: tag IS present
deploy:
  provider: script
  script: npm run release
  on:
    branch: master
    tags: true
